#!/bin/bash

# ============================================================
#  VITALIS PORTAL — Automated Setup Script
#  Vitalis Healthcare Services · v1.0
#  Mac/Linux compatible
# ============================================================

set -e

TEAL='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m' # No Colour

clear
echo ""
echo -e "${TEAL}${BOLD}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${TEAL}${BOLD}║        VITALIS PORTAL — Setup Wizard  v1.1       ║${NC}"
echo -e "${TEAL}${BOLD}║        Vitalis Healthcare Services                ║${NC}"
echo -e "${TEAL}${BOLD}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Check Node.js ────────────────────────────────────
echo -e "${BOLD}[1/5] Checking Node.js...${NC}"
if ! command -v node &> /dev/null; then
  echo -e "${RED}✗ Node.js not found.${NC}"
  echo ""
  echo "  Please install Node.js (v18 or higher) from:"
  echo "  https://nodejs.org/en/download"
  echo ""
  echo "  Or with Homebrew:  brew install node"
  echo ""
  exit 1
fi

NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
  echo -e "${RED}✗ Node.js v${NODE_VERSION} found. Version 18+ is required.${NC}"
  echo "  Please upgrade: https://nodejs.org"
  exit 1
fi
echo -e "${GREEN}✓ Node.js $(node -v) found${NC}"

# ── Step 2: Install dependencies ────────────────────────────
echo ""
echo -e "${BOLD}[2/5] Installing dependencies...${NC}"
echo "  (This may take 1-2 minutes on first run)"
npm install --silent
echo -e "${GREEN}✓ Dependencies installed${NC}"

# ── Step 3: Supabase credentials ────────────────────────────
echo ""
echo -e "${BOLD}[3/5] Supabase Configuration${NC}"
echo ""
echo -e "  You need a ${TEAL}free Supabase project${NC} for the database."
echo ""
echo -e "  ${YELLOW}If you haven't created one yet:${NC}"
echo "  1. Go to https://supabase.com → Sign up (free)"
echo "  2. Click 'New Project' → name it 'vitalis-portal'"
echo "  3. Go to Project Settings → API"
echo "  4. Copy the 'Project URL' and 'anon public' key"
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ] && grep -q "supabase.co" ".env.local" 2>/dev/null; then
  echo -e "${GREEN}✓ .env.local already configured — skipping${NC}"
  echo "  (Delete .env.local and re-run setup to reconfigure)"
else
  echo -e "${YELLOW}Enter your Supabase credentials:${NC}"
  echo ""
  
  read -p "  Supabase Project URL (https://xxx.supabase.co): " SUPABASE_URL
  if [ -z "$SUPABASE_URL" ]; then
    echo -e "${RED}✗ URL cannot be empty.${NC}"; exit 1
  fi
  
  read -p "  Supabase Anon Key: " SUPABASE_KEY
  if [ -z "$SUPABASE_KEY" ]; then
    echo -e "${RED}✗ Key cannot be empty.${NC}"; exit 1
  fi

  cat > .env.local << EOF
# Vitalis Portal — Environment Variables
# Generated by setup.sh on $(date)

NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_KEY}
NEXT_PUBLIC_APP_NAME=Vitalis Portal
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF

  echo -e "${GREEN}✓ .env.local created${NC}"
fi

# ── Step 4: Database reminder ────────────────────────────────
echo ""
echo -e "${BOLD}[4/5] Database Setup${NC}"
echo ""
echo -e "  ${YELLOW}⚠ IMPORTANT — Run these SQL files in your Supabase dashboard:${NC}"
echo ""
echo "  1. Go to supabase.com → your project → SQL Editor"
echo "  2. Run:  supabase/migrations/001_initial_schema.sql"
echo "  3. Run:  supabase/migrations/002_seed_data.sql"
echo ""
echo "  The SQL files are also printed in full in:"
echo -e "  ${TEAL}supabase/migrations/VITALIS_SQL_COMMANDS.txt${NC}"
echo ""
read -p "  Press Enter once you've run the migrations (or skip to do later)..."

# ── Step 5: Launch ────────────────────────────────────────────
echo ""
echo -e "${BOLD}[5/5] Launching Vitalis Portal...${NC}"
echo ""
echo -e "${GREEN}${BOLD}✓ Setup complete!${NC}"
echo ""
echo -e "  ${TEAL}Opening http://localhost:3000${NC}"
echo ""
echo "  First time? After the app loads:"
echo "  1. Sign up with your email"
echo "  2. In Supabase → Table Editor → profiles"
echo "     Set your role to 'admin'"
echo ""
echo -e "  ${YELLOW}Press Ctrl+C to stop the server${NC}"
echo ""

# Open browser after short delay
(sleep 3 && open "http://localhost:3000") &

npm run dev
