/**
 * lib/printUtils.ts
 * Shared print and Excel download helpers for Vitalis portal
 */

/** Open a new window with clean HTML and trigger print/save PDF */
export function printWindow(title: string, bodyHtml: string, css = '') {
  const defaultCss = `
    @page { margin: 14mm 16mm; size: A4 portrait; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
           font-size: 9pt; color: #111; background: #fff; padding: 0; }
    .page-header { border-bottom: 3px solid #0B6B5C; padding-bottom: 12px;
                   margin-bottom: 20px; display: flex; justify-content: space-between;
                   -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    h1 { font-size: 15pt; font-weight: 800; color: #0B6B5C;
         -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    h2 { font-size: 9pt; color: #666; font-weight: 400; margin-top: 3px; }
    h3 { font-size: 11pt; font-weight: 700; margin: 18px 0 8px;
         padding-bottom: 5px; border-bottom: 2px solid #0B6B5C;
         page-break-after: avoid; break-after: avoid;
         -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    table { width: 100%; border-collapse: collapse; margin: 8px 0;
            font-size: 8.5pt; page-break-inside: auto; }
    thead { display: table-header-group; }
    tr { page-break-inside: avoid; break-inside: avoid; }
    th { background: #0B6B5C; color: #fff; padding: 6px 8px; text-align: left;
         font-weight: 600; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    td { padding: 5px 8px; border-bottom: 1px solid #E5E7EB; }
    tr:nth-child(even) td { background: #F9FAFB;
                            -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .badge { display: inline-block; padding: 1px 6px; border-radius: 10px;
             font-size: 7.5pt; font-weight: 600;
             -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .badge-hot  { background: #D1FAE5; color: #065F46; }
    .badge-cold { background: #DBEAFE; color: #1E40AF; }
    .badge-dead { background: #FEE2E2; color: #991B1B; }
    .badge-f    { background: #D1FAE5; color: #065F46; }
    .badge-d    { background: #EDE9FE; color: #6D28D9; }
    .badge-x    { background: #FEF3C7; color: #B45309; }
    .stat-row   { display: flex; gap: 24px; margin-bottom: 16px; flex-wrap: wrap; }
    .stat-box   { text-align: center; }
    .stat-num   { font-size: 18pt; font-weight: 800; color: #0B6B5C; }
    .stat-lbl   { font-size: 7.5pt; color: #888; text-transform: uppercase; letter-spacing: 0.5px; }
    .footer     { margin-top: 32px; padding-top: 10px; border-top: 1px solid #E5E7EB;
                  font-size: 8pt; color: #AAA; display: flex; justify-content: space-between; }
  `
  const win = window.open('', '_blank', 'width=900,height=700')
  if (!win) { alert('Please allow pop-ups for this site to use Print.'); return }
  const dateStr = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
  win.document.write(`<!DOCTYPE html>
<html><head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>${defaultCss}${css}</style>
</head><body>
  <div class="page-header">
    <div>
      <h1>Vitalis Healthcare Services</h1>
      <h2>${title}</h2>
    </div>
    <div style="text-align:right;font-size:8pt;color:#888">
      <div>RSA #3879R · Silver Spring, MD</div>
      <div style="margin-top:3px">${dateStr}</div>
      <div style="margin-top:3px;color:#CCC">CONFIDENTIAL · Internal Use Only</div>
    </div>
  </div>
  ${bodyHtml}
  <div class="footer">
    <span>Generated by Vita AI · Vitalis Healthcare Portal</span>
    <span>Confidential — Internal Use Only</span>
  </div>
</body></html>`)
  win.document.close()
  win.focus()
  setTimeout(() => { win.print(); win.close() }, 600)
}

/** Download data as an Excel-compatible CSV file */
export function downloadExcel(filename: string, headers: string[], rows: (string | number | null | undefined)[][]) {
  const escape = (v: string | number | null | undefined) => {
    const s = v == null ? '' : String(v)
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? '"' + s.replace(/"/g, '""') + '"'
      : s
  }
  const csv = [
    headers.map(escape).join(','),
    ...rows.map(row => row.map(escape).join(','))
  ].join('\r\n')

  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename.endsWith('.csv') ? filename : filename + '.csv'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
