-- ============================================================
-- Migration 040: Candidate Onboarding — Foundation (v0.6.0)
-- Run in Supabase SQL Editor (one block; idempotent)
-- Creates: onb_candidates, onb_questions (+86 seed), onb_attempts
-- ============================================================

-- ── Candidates ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS onb_candidates (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),

  first_name                TEXT NOT NULL,
  last_name                 TEXT NOT NULL,
  email                     TEXT NOT NULL,

  -- 'invited' | 'testing' | 'test_passed' | 'applying'
  -- | 'application_submitted' | 'in_review' | 'axiscare_created'
  -- | 'converted' | 'withdrawn'
  status                    TEXT NOT NULL DEFAULT 'invited',

  access_token              TEXT,            -- sha256 hex of the raw magic-link token
  token_expires_at          TIMESTAMPTZ,

  invited_by                UUID REFERENCES profiles(id) ON DELETE SET NULL,
  invited_at                TIMESTAMPTZ NOT NULL DEFAULT now(),

  test_passed_at            TIMESTAMPTZ,
  application_submitted_at  TIMESTAMPTZ,
  axiscare_pushed_at        TIMESTAMPTZ,
  axiscare_applicant_id     INTEGER,
  converted_to_profile_id   UUID REFERENCES profiles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS onb_candidates_status_idx ON onb_candidates (status, created_at DESC);
CREATE INDEX IF NOT EXISTS onb_candidates_token_idx  ON onb_candidates (access_token);
CREATE INDEX IF NOT EXISTS onb_candidates_email_idx  ON onb_candidates (lower(email));

-- ── Competency questions ────────────────────────────────────
CREATE TABLE IF NOT EXISTS onb_questions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  domain        TEXT NOT NULL,
  prompt        TEXT NOT NULL,
  options       JSONB NOT NULL,          -- [{"key":"A","text":"..."}, ...]
  correct_key   TEXT NOT NULL,           -- 'A' | 'B' | 'C' | 'D'
  rationale     TEXT,
  active        BOOLEAN NOT NULL DEFAULT true,
  sort_order    INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS onb_questions_active_idx ON onb_questions (active, sort_order);

-- ── Test attempts ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS onb_attempts (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  candidate_id     UUID NOT NULL REFERENCES onb_candidates(id) ON DELETE CASCADE,
  first_score      INTEGER,
  first_total      INTEGER,
  first_passed     BOOLEAN,
  answers          JSONB,                -- {question_id: {selected, correct, attempts}}
  mastery_reached  BOOLEAN NOT NULL DEFAULT false,
  started_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS onb_attempts_candidate_idx ON onb_attempts (candidate_id, created_at DESC);

-- ── Seed: 86 competency questions ───────────────────────────
-- Re-runnable: clears the seeded bank, then re-inserts. Safe because
-- attempts store a snapshot of answers, not a FK to questions.
DELETE FROM onb_questions;
INSERT INTO onb_questions (domain, prompt, options, correct_key, rationale, sort_order) VALUES
  ('Communication & Interpersonal', 'A client is hard of hearing. The best way to help them understand you is to:', '[{"key": "A", "text": "Shout into their ear"}, {"key": "B", "text": "Speak in a higher pitch"}, {"key": "C", "text": "Face them and speak clearly at a normal pace"}, {"key": "D", "text": "Whisper to stay calm"}]'::jsonb, 'C', 'Facing the client lets them read lips and hear normally; shouting and high pitch distort sound.', 1),
  ('Communication & Interpersonal', 'A neighbor stops the aide and asks, "Is Mr. Davis dying?" The best reply is:', '[{"key": "A", "text": "\"Yes, he''s very ill.\""}, {"key": "B", "text": "\"I''m sorry, I can''t discuss Mr. Davis.\""}, {"key": "C", "text": "\"How did you hear that?\""}, {"key": "D", "text": "\"He''s doing as well as can be expected.\""}]'::jsonb, 'B', 'Client information is private and is not shared with others.', 2),
  ('Communication & Interpersonal', 'A client wants to talk about a personal worry. The aide should:', '[{"key": "A", "text": "Change the subject"}, {"key": "B", "text": "Give their own advice"}, {"key": "C", "text": "Listen and let the client share their feelings"}, {"key": "D", "text": "Tell them to call family"}]'::jsonb, 'C', 'Active listening supports the client without overstepping the aide''s role.', 3),
  ('Communication & Interpersonal', 'Which shows good communication with a client?', '[{"key": "A", "text": "Talking about your own life"}, {"key": "B", "text": "Finishing their sentences"}, {"key": "C", "text": "Asking questions and listening"}, {"key": "D", "text": "Speaking to the family instead"}]'::jsonb, 'C', 'Good communication centers on the client and uses open listening.', 4),
  ('Communication & Interpersonal', 'A client who had a stroke struggles to find words. The aide should:', '[{"key": "A", "text": "Speak for them to save time"}, {"key": "B", "text": "Give them time and watch for gestures"}, {"key": "C", "text": "Pretend to understand"}, {"key": "D", "text": "Raise their voice"}]'::jsonb, 'B', 'Patience and nonverbal cues help; their hearing is usually fine.', 5),
  ('Communication & Interpersonal', 'A client speaks little English. The best first step is to:', '[{"key": "A", "text": "Speak louder"}, {"key": "B", "text": "Use simple words, gestures, and pictures"}, {"key": "C", "text": "Skip the conversation"}, {"key": "D", "text": "Ask a stranger to translate"}]'::jsonb, 'B', 'Simple words and visuals bridge a language gap respectfully and privately.', 6),
  ('Client Rights, HIPAA & Confidentiality', 'A client holds religious beliefs the aide does not share. The aide should:', '[{"key": "A", "text": "Explain why theirs are better"}, {"key": "B", "text": "Respect the client''s right to their beliefs"}, {"key": "C", "text": "Tell them not to discuss it"}, {"key": "D", "text": "Pretend to agree"}]'::jsonb, 'B', 'Clients have the right to their own beliefs.', 7),
  ('Client Rights, HIPAA & Confidentiality', 'HIPAA mainly protects a client''s:', '[{"key": "A", "text": "Property"}, {"key": "B", "text": "Private health information"}, {"key": "C", "text": "Choice of visitors"}, {"key": "D", "text": "Choice of caregiver"}]'::jsonb, 'B', 'HIPAA safeguards protected health information.', 8),
  ('Client Rights, HIPAA & Confidentiality', 'A client asks to read the notes the aide just wrote about their care. The aide should:', '[{"key": "A", "text": "Refuse — notes are staff-only"}, {"key": "B", "text": "Allow them to read the notes"}, {"key": "C", "text": "Say only the supervisor may see them"}, {"key": "D", "text": "Tear them up"}]'::jsonb, 'B', 'Clients may see information about their own care.', 9),
  ('Client Rights, HIPAA & Confidentiality', 'Which is a breach of confidentiality?', '[{"key": "A", "text": "Reporting a fall to the nurse"}, {"key": "B", "text": "Telling your spouse the client''s diagnosis"}, {"key": "C", "text": "Writing the visit note"}, {"key": "D", "text": "Telling the nurse about a skin change"}]'::jsonb, 'B', 'Sharing client information with people not involved in care breaks confidentiality.', 10),
  ('Client Rights, HIPAA & Confidentiality', 'A client refuses a bath today. The aide should:', '[{"key": "A", "text": "Bathe them anyway"}, {"key": "B", "text": "Respect the refusal and report it"}, {"key": "C", "text": "Tell them they must comply"}, {"key": "D", "text": "Skip the whole visit"}]'::jsonb, 'B', 'Clients may refuse care; the aide reports the refusal.', 11),
  ('Client Rights, HIPAA & Confidentiality', 'Posting a photo of a client on social media is:', '[{"key": "A", "text": "Fine if they look happy"}, {"key": "B", "text": "Okay without their name"}, {"key": "C", "text": "A serious privacy breach"}, {"key": "D", "text": "Okay when off duty"}]'::jsonb, 'C', 'Sharing client images without authorization violates privacy, on or off duty.', 12),
  ('Client Rights, HIPAA & Confidentiality', 'Knocking before entering a client''s room respects their:', '[{"key": "A", "text": "Schedule"}, {"key": "B", "text": "Privacy and dignity"}, {"key": "C", "text": "Property"}, {"key": "D", "text": "Diet"}]'::jsonb, 'B', 'Small courtesies protect privacy and dignity.', 13),
  ('Legal/Ethical, Professional Boundaries & Reporting', 'An aide suspects a family member is abusing a client. The aide must:', '[{"key": "A", "text": "Confront the family member"}, {"key": "B", "text": "Wait and watch"}, {"key": "C", "text": "Report it to the supervisor right away"}, {"key": "D", "text": "Keep it quiet"}]'::jsonb, 'C', 'Suspected abuse is reported promptly; aides report, not investigate.', 14),
  ('Legal/Ethical, Professional Boundaries & Reporting', 'A client wrongly accuses the aide of stealing money. The aide should:', '[{"key": "A", "text": "Replace the money"}, {"key": "B", "text": "Argue"}, {"key": "C", "text": "Notify the supervisor"}, {"key": "D", "text": "Ask other aides if they took it"}]'::jsonb, 'C', 'The aide reports the accusation and does not handle it alone.', 15),
  ('Legal/Ethical, Professional Boundaries & Reporting', 'Which is within an aide''s scope?', '[{"key": "A", "text": "Give an injection"}, {"key": "B", "text": "Change a sterile dressing"}, {"key": "C", "text": "Report a client''s reaction to medication"}, {"key": "D", "text": "Adjust a medication dose"}]'::jsonb, 'C', 'Observing and reporting is allowed; clinical tasks and dosing are not.', 16),
  ('Legal/Ethical, Professional Boundaries & Reporting', 'A client offers the aide an expensive gift. The aide should:', '[{"key": "A", "text": "Accept to avoid offense"}, {"key": "B", "text": "Politely decline and tell the supervisor"}, {"key": "C", "text": "Take it quietly"}, {"key": "D", "text": "Ask for cash instead"}]'::jsonb, 'B', 'Gifts are a conflict of interest; decline and report.', 17),
  ('Legal/Ethical, Professional Boundaries & Reporting', 'Leaving a client who needs supervision alone to run a personal errand is:', '[{"key": "A", "text": "Fine if quick"}, {"key": "B", "text": "Neglect"}, {"key": "C", "text": "Okay if they agree"}, {"key": "D", "text": "Allowed on break"}]'::jsonb, 'B', 'Abandoning a client who needs supervision is neglect.', 18),
  ('Legal/Ethical, Professional Boundaries & Reporting', 'During a visit, a client keeps asking about the aide''s personal life and money troubles. The aide should:', '[{"key": "A", "text": "Share all the details to bond"}, {"key": "B", "text": "Keep the focus on the client and stay professional"}, {"key": "C", "text": "Complain about their own problems"}, {"key": "D", "text": "Ask the client for personal advice"}]'::jsonb, 'B', 'Over-sharing personal information crosses a professional boundary; care stays focused on the client.', 19),
  ('Legal/Ethical, Professional Boundaries & Reporting', 'A client hands the aide cash and a debit card and asks them to go shopping alone. The aide should:', '[{"key": "A", "text": "Take the money and run the errand"}, {"key": "B", "text": "Decline the money, offer to go together with the client, and tell the agency"}, {"key": "C", "text": "Keep the card for next time"}, {"key": "D", "text": "Use their own money and get paid back later"}]'::jsonb, 'B', 'Vitalis aides never take a client''s cash or cards to shop alone — they accompany the client and refer the request to the agency.', 20),
  ('Role, Scope of Practice & the Care Team', 'Which may an aide NOT do?', '[{"key": "A", "text": "Help a client walk"}, {"key": "B", "text": "Take a phone order from a doctor"}, {"key": "C", "text": "Assist with bathing"}, {"key": "D", "text": "Prepare a meal"}]'::jsonb, 'B', 'Taking medical orders is outside the aide''s scope.', 21),
  ('Role, Scope of Practice & the Care Team', 'The goal when caring for a person with a disability is to:', '[{"key": "A", "text": "Do everything for them"}, {"key": "B", "text": "Supervise constantly"}, {"key": "C", "text": "Promote the most self-care and independence possible"}, {"key": "D", "text": "Restore all lost abilities"}]'::jsonb, 'C', 'Care maximizes independence within the client''s ability.', 22),
  ('Role, Scope of Practice & the Care Team', 'The aide notices a problem beyond their training. They should:', '[{"key": "A", "text": "Fix it themselves"}, {"key": "B", "text": "Ignore it"}, {"key": "C", "text": "Report it to the nurse supervisor"}, {"key": "D", "text": "Ask the client what to do"}]'::jsonb, 'C', 'Aides report issues beyond their role.', 23),
  ('Role, Scope of Practice & the Care Team', 'The aide''s first point of contact for care questions is:', '[{"key": "A", "text": "The client''s doctor"}, {"key": "B", "text": "The agency/nurse supervisor"}, {"key": "C", "text": "The family"}, {"key": "D", "text": "A coworker"}]'::jsonb, 'B', 'The nurse supervisor directs the client''s care.', 24),
  ('Role, Scope of Practice & the Care Team', 'The care plan / task list tells the aide:', '[{"key": "A", "text": "The full medical history"}, {"key": "B", "text": "The specific tasks and limits for that client"}, {"key": "C", "text": "Insurance details"}, {"key": "D", "text": "Nothing they must follow"}]'::jsonb, 'B', 'The care plan defines what the aide may and may not do.', 25),
  ('Role, Scope of Practice & the Care Team', 'A client asks the aide to do a task not on the care plan. The aide should:', '[{"key": "A", "text": "Do it to help"}, {"key": "B", "text": "Decline and direct the request to the agency"}, {"key": "C", "text": "Do it once"}, {"key": "D", "text": "Have the client sign for it"}]'::jsonb, 'B', 'Aides follow the task list and send new requests to the agency.', 26),
  ('Infection Control & Standard Precautions', 'The single best way to stop the spread of infection is:', '[{"key": "A", "text": "A mask"}, {"key": "B", "text": "Hand hygiene"}, {"key": "C", "text": "Gloves all day"}, {"key": "D", "text": "Open windows"}]'::jsonb, 'B', 'Handwashing is the top defense against spreading germs.', 27),
  ('Infection Control & Standard Precautions', 'Hands should be washed with soap and water (not just sanitizer) when:', '[{"key": "A", "text": "They look clean"}, {"key": "B", "text": "They are visibly dirty or soiled, or after the toilet"}, {"key": "C", "text": "Always, never use sanitizer"}, {"key": "D", "text": "Only at shift start"}]'::jsonb, 'B', 'Sanitizer is fine for routine cleaning, but visibly soiled hands need soap and water.', 28),
  ('Infection Control & Standard Precautions', 'An aide should wash their hands:', '[{"key": "A", "text": "Only before meals"}, {"key": "B", "text": "Only after the toilet"}, {"key": "C", "text": "Before and after client care"}, {"key": "D", "text": "Once per shift"}]'::jsonb, 'C', 'Hands are washed before and after care and any time they may be soiled.', 29),
  ('Infection Control & Standard Precautions', 'Which is a sign of a possible infection to report?', '[{"key": "A", "text": "Increased appetite"}, {"key": "B", "text": "Redness, swelling, and warmth at a site"}, {"key": "C", "text": "Clear urine"}, {"key": "D", "text": "Steady weight"}]'::jsonb, 'B', 'Redness, swelling, warmth, pain, and fever can signal infection.', 30),
  ('Infection Control & Standard Precautions', 'After removing soiled gloves, the aide should:', '[{"key": "A", "text": "Reuse them"}, {"key": "B", "text": "Wash their hands"}, {"key": "C", "text": "Pocket them"}, {"key": "D", "text": "Rinse and reuse"}]'::jsonb, 'B', 'Hands are washed after glove removal; gloves are not foolproof.', 31),
  ('Infection Control & Standard Precautions', 'Standard precautions mean treating which fluids as possibly infectious?', '[{"key": "A", "text": "Only blood"}, {"key": "B", "text": "Only urine"}, {"key": "C", "text": "All blood and body fluids"}, {"key": "D", "text": "None if the client looks well"}]'::jsonb, 'C', 'All blood and body fluids are treated as potentially infectious.', 32),
  ('Infection Control & Standard Precautions', 'When should the aide wear gloves?', '[{"key": "A", "text": "Never"}, {"key": "B", "text": "When cleaning or in contact with body fluids"}, {"key": "C", "text": "Only outdoors"}, {"key": "D", "text": "Only if the client asks"}]'::jsonb, 'B', 'Gloves are worn for cleaning and any contact with blood or body fluids.', 33),
  ('Infection Control & Standard Precautions', 'An aide has a small open cut on their hand. Before care they should:', '[{"key": "A", "text": "Ignore it"}, {"key": "B", "text": "Cover it and wear gloves"}, {"key": "C", "text": "Skip handwashing"}, {"key": "D", "text": "Wait for it to heal"}]'::jsonb, 'B', 'Open skin is covered and gloves worn to protect both people.', 34),
  ('Safety, Body Mechanics & Emergency Response', 'When lifting from the floor, the aide should:', '[{"key": "A", "text": "Bend at the waist"}, {"key": "B", "text": "Keep legs straight"}, {"key": "C", "text": "Bend the knees, keep the back straight"}, {"key": "D", "text": "Hold the load far from the body"}]'::jsonb, 'C', 'Bending the knees with a straight back protects the aide''s back.', 35),
  ('Safety, Body Mechanics & Emergency Response', 'A client starts to fall while walking. The aide should:', '[{"key": "A", "text": "Grab their arms to stop it"}, {"key": "B", "text": "Let them drop"}, {"key": "C", "text": "Ease them gently to the floor, bending the knees"}, {"key": "D", "text": "Step away"}]'::jsonb, 'C', 'Easing the client down protects both people from injury.', 36),
  ('Safety, Body Mechanics & Emergency Response', 'A client has crushing chest pain spreading down the arm and is sweating. The aide should first:', '[{"key": "A", "text": "Apply a warm compress"}, {"key": "B", "text": "Call 911"}, {"key": "C", "text": "Massage the chest"}, {"key": "D", "text": "Have them lie face down"}]'::jsonb, 'B', 'These are heart-attack signs; emergency help is called immediately.', 37),
  ('Safety, Body Mechanics & Emergency Response', 'If a client stops breathing, the aide should first:', '[{"key": "A", "text": "Pinch to wake them"}, {"key": "B", "text": "Clear the mouth and call for help"}, {"key": "C", "text": "Raise the legs"}, {"key": "D", "text": "Press on the neck"}]'::jsonb, 'B', 'Open/clear the airway and get emergency help right away.', 38),
  ('Safety, Body Mechanics & Emergency Response', 'Before first aid for choking, the aide should find out:', '[{"key": "A", "text": "The pulse rate"}, {"key": "B", "text": "Whether the client can speak or cough"}, {"key": "C", "text": "If they took medicine"}, {"key": "D", "text": "Their temperature"}]'::jsonb, 'B', 'If they can speak or cough, the airway isn''t fully blocked — encourage coughing.', 39),
  ('Safety, Body Mechanics & Emergency Response', 'The safe way to put out a small grease fire in a pan is to:', '[{"key": "A", "text": "Pour water on it"}, {"key": "B", "text": "Smother it with a lid or baking soda"}, {"key": "C", "text": "Fan it"}, {"key": "D", "text": "Add sugar"}]'::jsonb, 'B', 'Water spreads a grease fire; smothering removes the oxygen.', 40),
  ('Safety, Body Mechanics & Emergency Response', 'To help prevent falls, the aide should:', '[{"key": "A", "text": "Use loose throw rugs"}, {"key": "B", "text": "Keep walkways clear and well lit"}, {"key": "C", "text": "Leave cords on the floor"}, {"key": "D", "text": "Dim the lights"}]'::jsonb, 'B', 'Clear, lit walkways reduce trip hazards.', 41),
  ('Safety, Body Mechanics & Emergency Response', 'Moving a client up in bed alone, the aide should first:', '[{"key": "A", "text": "Lower both side rails"}, {"key": "B", "text": "Raise the bed to a safe working height"}, {"key": "C", "text": "Reach and twist"}, {"key": "D", "text": "Pull in one big motion"}]'::jsonb, 'B', 'Raising the bed avoids the bending and twisting that strain the back.', 42),
  ('Safety, Body Mechanics & Emergency Response', 'A client is on oxygen. The aide must ensure that:', '[{"key": "A", "text": "No one smokes near it"}, {"key": "B", "text": "The TV is unplugged"}, {"key": "C", "text": "The client drinks no soda"}, {"key": "D", "text": "The curtains stay shut"}]'::jsonb, 'A', 'Oxygen feeds fire; flames and smoking are dangerous near it.', 43),
  ('Safety, Body Mechanics & Emergency Response', 'The aide finds a client on the floor after a fall. The first action is to:', '[{"key": "A", "text": "Help them up fast"}, {"key": "B", "text": "Check for injury and call for help"}, {"key": "C", "text": "Move them to bed"}, {"key": "D", "text": "Finish chores first"}]'::jsonb, 'B', 'Check for injury before moving; moving an injured client can cause harm.', 44),
  ('ADLs — Hygiene, Dressing, Grooming, Elimination', 'Before a bed bath, the aide checks the water temperature by:', '[{"key": "A", "text": "Asking the client to test it"}, {"key": "B", "text": "Using their own inner wrist"}, {"key": "C", "text": "Letting it cool on its own"}, {"key": "D", "text": "Mixing hot and cold without checking"}]'::jsonb, 'B', 'The inner wrist is sensitive and safe for checking against burns.', 45),
  ('ADLs — Hygiene, Dressing, Grooming, Elimination', 'When washing the genital area, the aide cleans:', '[{"key": "A", "text": "Back toward the front"}, {"key": "B", "text": "Front to back"}, {"key": "C", "text": "Any direction"}, {"key": "D", "text": "With hot water only"}]'::jsonb, 'B', 'Front to back prevents spreading germs to the urinary area.', 46),
  ('ADLs — Hygiene, Dressing, Grooming, Elimination', 'Dressing a client with a weak arm, the aide puts on:', '[{"key": "A", "text": "The strong arm first"}, {"key": "B", "text": "The weak arm first"}, {"key": "C", "text": "Pulls the weak arm hard"}, {"key": "D", "text": "Dresses them standing"}]'::jsonb, 'B', 'Dressing the weak side first reduces strain and discomfort.', 47),
  ('ADLs — Hygiene, Dressing, Grooming, Elimination', 'Good mouth care matters because:', '[{"key": "A", "text": "It increases saliva"}, {"key": "B", "text": "Mouth bacteria can cause infection"}, {"key": "C", "text": "It worsens taste"}, {"key": "D", "text": "It replaces brushing"}]'::jsonb, 'B', 'Oral bacteria can cause decay and gum infection if not cleaned.', 48),
  ('ADLs — Hygiene, Dressing, Grooming, Elimination', 'Routine denture care includes:', '[{"key": "A", "text": "Storing them dry"}, {"key": "B", "text": "Cleaning over a towel or water-filled basin"}, {"key": "C", "text": "Soaking in hot water"}, {"key": "D", "text": "Brushing with bleach"}]'::jsonb, 'B', 'Cleaning over a soft surface or water prevents breakage if dropped.', 49),
  ('ADLs — Hygiene, Dressing, Grooming, Elimination', 'A client sometimes wets themselves. The best response is to:', '[{"key": "A", "text": "Limit all fluids"}, {"key": "B", "text": "Offer regular bathroom trips, e.g. every two hours"}, {"key": "C", "text": "Warn them about diapers"}, {"key": "D", "text": "Cut fluids after noon"}]'::jsonb, 'B', 'Scheduled toileting supports continence and dignity without harmful fluid limits.', 50),
  ('ADLs — Hygiene, Dressing, Grooming, Elimination', 'With an indwelling catheter, the drainage bag is kept:', '[{"key": "A", "text": "Above the bladder"}, {"key": "B", "text": "Below the bladder"}, {"key": "C", "text": "On the bed"}, {"key": "D", "text": "Clamped during care"}]'::jsonb, 'B', 'Below bladder level prevents urine from flowing back.', 51),
  ('ADLs — Hygiene, Dressing, Grooming, Elimination', 'To help prevent pressure sores on bed rest, the aide should:', '[{"key": "A", "text": "Tuck the top sheet tight"}, {"key": "B", "text": "Keep the bottom sheet smooth and reposition often"}, {"key": "C", "text": "Use only wool blankets"}, {"key": "D", "text": "Keep one position"}]'::jsonb, 'B', 'Smooth linens and frequent repositioning protect the skin.', 52),
  ('ADLs — Hygiene, Dressing, Grooming, Elimination', 'Pressure sores are most likely over:', '[{"key": "A", "text": "Soft, fatty areas"}, {"key": "B", "text": "Bony areas like hips and heels"}, {"key": "C", "text": "The palms"}, {"key": "D", "text": "The abdomen"}]'::jsonb, 'B', 'Bony prominences bear the most pressure and break down first.', 53),
  ('Nutrition, Hydration & Special Diets', 'A good source of protein is:', '[{"key": "A", "text": "Apples and oranges"}, {"key": "B", "text": "Potatoes and noodles"}, {"key": "C", "text": "Beans, eggs, and peanut butter"}, {"key": "D", "text": "Lettuce and cucumber"}]'::jsonb, 'C', 'Beans, eggs, and peanut butter are protein-rich.', 54),
  ('Nutrition, Hydration & Special Diets', 'On a low-salt diet, the better choice is:', '[{"key": "A", "text": "Ham sandwich and chips"}, {"key": "B", "text": "Hot dog and pickles"}, {"key": "C", "text": "Turkey sandwich and fruit"}, {"key": "D", "text": "Canned soup and crackers"}]'::jsonb, 'C', 'Processed meats, pickles, and canned soup are high in salt.', 55),
  ('Nutrition, Hydration & Special Diets', 'Fiber in the diet helps to:', '[{"key": "A", "text": "Build bones"}, {"key": "B", "text": "Prevent constipation"}, {"key": "C", "text": "Make red blood cells"}, {"key": "D", "text": "Thin the blood"}]'::jsonb, 'B', 'Fiber adds bulk and keeps the bowels moving.', 56),
  ('Nutrition, Hydration & Special Diets', 'A client with diabetes on insulin feels shaky and nervous. The aide should:', '[{"key": "A", "text": "Take their temperature"}, {"key": "B", "text": "Give a quick sugar source like juice"}, {"key": "C", "text": "Have them lie down and wait"}, {"key": "D", "text": "Book a doctor visit"}]'::jsonb, 'B', 'Shakiness can mean low blood sugar; give fast sugar, then report.', 57),
  ('Nutrition, Hydration & Special Diets', 'Keeping a fluid intake record, the aide records fluids:', '[{"key": "A", "text": "When served"}, {"key": "B", "text": "After the client drinks them"}, {"key": "C", "text": "Every two hours"}, {"key": "D", "text": "From memory at day''s end"}]'::jsonb, 'B', 'Intake is recorded after it is actually consumed.', 58),
  ('Nutrition, Hydration & Special Diets', 'A client isn''t hungry at their usual lunchtime for the first time. The aide should:', '[{"key": "A", "text": "Insist they eat now"}, {"key": "B", "text": "Note it, encourage eating, and offer food later"}, {"key": "C", "text": "Warn they''ll be hand-fed"}, {"key": "D", "text": "Throw the food out"}]'::jsonb, 'B', 'Respect the client, encourage intake, and report the change.', 59),
  ('Observation, Documentation & Reporting — AxisCare / EVV', 'In AxisCare, a caregiver can clock in or out for a visit:', '[{"key": "A", "text": "From anywhere, if it''s on time"}, {"key": "B", "text": "Only when at the client''s location"}, {"key": "C", "text": "From home before leaving"}, {"key": "D", "text": "Up to an hour early"}]'::jsonb, 'B', 'EVV blocks clock-in or clock-out when the caregiver is not at the client''s home.', 60),
  ('Observation, Documentation & Reporting — AxisCare / EVV', 'A caregiver finishes a visit but doesn''t complete the ADLs and visit note. As a result:', '[{"key": "A", "text": "The office fills them in later"}, {"key": "B", "text": "The visit is paid as normal"}, {"key": "C", "text": "The shift can''t be verified and won''t be paid"}, {"key": "D", "text": "Only the note matters, not ADLs"}]'::jsonb, 'C', 'Without completed ADLs and visit notes, a Vitalis shift can''t be verified, so it isn''t paid.', 61),
  ('Observation, Documentation & Reporting — AxisCare / EVV', 'A caregiver wants to clock in 20 minutes before the shift starts. They should:', '[{"key": "A", "text": "Clock in early — it''s fine"}, {"key": "B", "text": "Call the agency first"}, {"key": "C", "text": "Clock in late instead"}, {"key": "D", "text": "Skip clocking in"}]'::jsonb, 'B', 'You can''t clock in 15 minutes or more before a shift without calling the agency.', 62),
  ('Observation, Documentation & Reporting — AxisCare / EVV', 'Which visit note is written correctly?', '[{"key": "A", "text": "\"I chilled all day\""}, {"key": "B", "text": "\"Just cleaned\""}, {"key": "C", "text": "\"Provided companionship and tidied the kitchen\""}, {"key": "D", "text": "\"Nothing happened\""}]'::jsonb, 'C', 'Notes should be specific and professional about the care given.', 63),
  ('Observation, Documentation & Reporting — AxisCare / EVV', 'Visit notes should be written:', '[{"key": "A", "text": "In future tense"}, {"key": "B", "text": "In past tense, e.g. \"I helped…\""}, {"key": "C", "text": "In slang"}, {"key": "D", "text": "In short codes"}]'::jsonb, 'B', 'Notes describe care already given; slang and emojis are avoided.', 64),
  ('Observation, Documentation & Reporting — AxisCare / EVV', 'A client seemed mixed up and forgetful during the visit. The best note is:', '[{"key": "A", "text": "\"Client was weird\""}, {"key": "B", "text": "\"Client appeared confused at times; I informed the nurse\""}, {"key": "C", "text": "\"Nothing to report\""}, {"key": "D", "text": "\"Client acted crazy\""}]'::jsonb, 'B', 'Notes stay specific and professional, and changes are reported to the nurse.', 65),
  ('Observation, Documentation & Reporting — AxisCare / EVV', 'Every visit note should include:', '[{"key": "A", "text": "The aide''s opinion of the family"}, {"key": "B", "text": "Arrival and departure times and care given"}, {"key": "C", "text": "Only the client''s mood"}, {"key": "D", "text": "A guess at the diagnosis"}]'::jsonb, 'B', 'Required elements include exact times, services provided, and the client''s condition.', 66),
  ('Observation, Documentation & Reporting — AxisCare / EVV', 'A caregiver forgot to record one task during the visit. They should:', '[{"key": "A", "text": "Make up a time that looks right"}, {"key": "B", "text": "Record only what truly happened"}, {"key": "C", "text": "Copy last week''s note"}, {"key": "D", "text": "Leave the note blank"}]'::jsonb, 'B', 'Notes are legal documents; never fabricate — record only what actually occurred.', 67),
  ('Observation, Documentation & Reporting — AxisCare / EVV', 'Beyond daily care, accurate visit notes matter because they are:', '[{"key": "A", "text": "Just for the caregiver"}, {"key": "B", "text": "Legal records used for insurance and Medicaid"}, {"key": "C", "text": "A replacement for the care plan"}, {"key": "D", "text": "Optional"}]'::jsonb, 'B', 'Notes provide legal protection and meet insurance and Medicaid requirements.', 68),
  ('Observation, Documentation & Reporting — AxisCare / EVV', 'A caregiver sees that a task they always do for this client is missing from the ADL list. They should:', '[{"key": "A", "text": "Skip the task"}, {"key": "B", "text": "Contact the agency as soon as possible"}, {"key": "C", "text": "Add a brand-new service on their own"}, {"key": "D", "text": "Do nothing"}]'::jsonb, 'B', 'If a usual ADL isn''t listed, contact the agency ASAP so it can be corrected.', 69),
  ('Vital Signs & Basic Clinical Skills', 'To count respirations, the aide counts:', '[{"key": "A", "text": "Each rise and fall as two breaths"}, {"key": "B", "text": "Each full rise and fall as one breath"}, {"key": "C", "text": "For 10 seconds"}, {"key": "D", "text": "While telling the client to breathe"}]'::jsonb, 'B', 'One full rise and fall equals one respiration; don''t cue the client.', 70),
  ('Vital Signs & Basic Clinical Skills', 'The thumb isn''t used to take a pulse because:', '[{"key": "A", "text": "It''s too short"}, {"key": "B", "text": "It has its own pulse that can be felt"}, {"key": "C", "text": "It''s less clean"}, {"key": "D", "text": "It tires quickly"}]'::jsonb, 'B', 'The thumb''s own pulse can be mistaken for the client''s.', 71),
  ('Vital Signs & Basic Clinical Skills', 'Which oral temperature should be reported?', '[{"key": "A", "text": "98.6°F"}, {"key": "B", "text": "97.6°F"}, {"key": "C", "text": "100.2°F"}, {"key": "D", "text": "98.2°F"}]'::jsonb, 'C', '100.2°F is a fever; the others are normal.', 72),
  ('Vital Signs & Basic Clinical Skills', 'The aide should take an oral temperature only when the client:', '[{"key": "A", "text": "Just drank hot coffee"}, {"key": "B", "text": "Has waited after eating or drinking"}, {"key": "C", "text": "Is short of breath"}, {"key": "D", "text": "Is chewing gum"}]'::jsonb, 'B', 'Hot or cold intake changes the reading; wait first.', 73),
  ('Vital Signs & Basic Clinical Skills', 'Circulation generally improves when the client''s:', '[{"key": "A", "text": "Room is kept cold"}, {"key": "B", "text": "Activity is increased"}, {"key": "C", "text": "Fluids are limited"}, {"key": "D", "text": "Clothing is loosened"}]'::jsonb, 'B', 'Movement promotes blood flow.', 74),
  ('Vital Signs & Basic Clinical Skills', 'When taking blood pressure, the aide should:', '[{"key": "A", "text": "Place the cuff over thick clothing"}, {"key": "B", "text": "Use a bare upper arm at heart level"}, {"key": "C", "text": "Let the client stand and talk"}, {"key": "D", "text": "Pump as hard as possible"}]'::jsonb, 'B', 'A bare arm at heart level gives an accurate, comfortable reading.', 75),
  ('Mobility, Transfers, Positioning & Restorative Care', 'When using a gait/transfer belt, the aide:', '[{"key": "A", "text": "Places it on bare skin"}, {"key": "B", "text": "Applies it snugly at the waist over clothing"}, {"key": "C", "text": "Places it at the chest"}, {"key": "D", "text": "Tightens it enough to limit breathing"}]'::jsonb, 'B', 'The belt goes snugly at the waist over clothing, never tight enough to restrict breathing.', 76),
  ('Mobility, Transfers, Positioning & Restorative Care', 'Moving a client from bed to wheelchair, the aide must first:', '[{"key": "A", "text": "Drape a blanket"}, {"key": "B", "text": "Lock the wheelchair brakes"}, {"key": "C", "text": "Add a seat pillow"}, {"key": "D", "text": "Remove and leave off the footrests"}]'::jsonb, 'B', 'Locking the brakes keeps the chair from rolling.', 77),
  ('Mobility, Transfers, Positioning & Restorative Care', 'Helping a client weak on one side to walk, the aide stands:', '[{"key": "A", "text": "Directly in front"}, {"key": "B", "text": "On the weak side"}, {"key": "C", "text": "Far behind"}, {"key": "D", "text": "On the strong side"}]'::jsonb, 'B', 'Standing on the weak side gives support where it''s needed.', 78),
  ('Mobility, Transfers, Positioning & Restorative Care', 'During range-of-motion exercises, the aide should:', '[{"key": "A", "text": "Force the joint past resistance"}, {"key": "B", "text": "Support the limb above and below the joint"}, {"key": "C", "text": "Skip explaining to a client who can''t talk"}, {"key": "D", "text": "Move one joint once"}]'::jsonb, 'B', 'Supporting above and below moves the joint safely.', 79),
  ('Mobility, Transfers, Positioning & Restorative Care', 'A client on bed rest sits up and feels dizzy. The aide should:', '[{"key": "A", "text": "Help them stand to walk it off"}, {"key": "B", "text": "Support them sitting and wait a moment"}, {"key": "C", "text": "Lay them flat and leave"}, {"key": "D", "text": "Rub their feet"}]'::jsonb, 'B', 'Letting dizziness pass while supported and seated prevents a fall.', 80),
  ('Mental Health, Dementia, End-of-Life & Spiritual/Cultural', 'A client with dementia becomes confused and upset. The best approach is to:', '[{"key": "A", "text": "Argue with the false belief"}, {"key": "B", "text": "Stay calm, reassure, and redirect"}, {"key": "C", "text": "Raise your voice"}, {"key": "D", "text": "Leave the room"}]'::jsonb, 'B', 'A calm redirect reduces agitation; arguing increases it.', 81),
  ('Mental Health, Dementia, End-of-Life & Spiritual/Cultural', 'A client recently out of a mental health unit says, "I hear a voice telling me what to do." The aide should:', '[{"key": "A", "text": "Ignore it"}, {"key": "B", "text": "Report it to the supervisor right away"}, {"key": "C", "text": "Tell them to stop listening"}, {"key": "D", "text": "Wait until next visit"}]'::jsonb, 'B', 'Hearing voices is a serious symptom that must be reported promptly.', 82),
  ('Mental Health, Dementia, End-of-Life & Spiritual/Cultural', 'Caring for an unconscious, terminally ill client, the aide should:', '[{"key": "A", "text": "Stop talking"}, {"key": "B", "text": "Explain each thing they''re doing"}, {"key": "C", "text": "Keep the room fully dark"}, {"key": "D", "text": "Give only clear liquids"}]'::jsonb, 'B', 'Hearing may remain; explaining care shows respect and may comfort.', 83),
  ('Mental Health, Dementia, End-of-Life & Spiritual/Cultural', 'A client says, "I hate not being able to care for myself." The best reply is:', '[{"key": "A", "text": "\"You shouldn''t feel that way.\""}, {"key": "B", "text": "\"It''s hard to need help when you''re used to being independent.\""}, {"key": "C", "text": "\"You should be glad for the help.\""}, {"key": "D", "text": "\"Let''s not talk about it.\""}]'::jsonb, 'B', 'Reflecting feelings shows empathy and respect.', 84),
  ('Mental Health, Dementia, End-of-Life & Spiritual/Cultural', 'Letting a client choose clothes and help plan their day is good because it:', '[{"key": "A", "text": "Cuts the aide''s workload"}, {"key": "B", "text": "Stops complaints"}, {"key": "C", "text": "Helps the client keep a sense of control"}, {"key": "D", "text": "Shows they need help"}]'::jsonb, 'C', 'Offering choices supports dignity and control.', 85),
  ('Mental Health, Dementia, End-of-Life & Spiritual/Cultural', 'A client asks the aide to pray with them in a faith different from the aide''s. The aide should:', '[{"key": "A", "text": "Refuse and explain their own beliefs"}, {"key": "B", "text": "Respectfully support the client''s wishes"}, {"key": "C", "text": "Say prayer won''t help"}, {"key": "D", "text": "Report the client"}]'::jsonb, 'B', 'Supporting spiritual and cultural needs respects the client''s rights and dignity.', 86);

-- ── Verify ──────────────────────────────────────────────────
-- SELECT count(*) FROM onb_questions;                 -- expect 86
-- SELECT domain, count(*) FROM onb_questions GROUP BY domain ORDER BY min(sort_order);

